export const providers = [
    {
      "UKPRN": 10000291,
      "PROVIDER_NAME": "ANGLIA RUSKIN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "BISHOP HALL LANE",
      "LOCALITY": "",
      "TOWN": "CHELMSFORD",
      "COUNTY": "",
      "POSTCODE": "CM1 1SQ",
      "WEBSITE_ADDRESS": "www.anglia.ac.uk"
    },
    {
      "UKPRN": 10000385,
      "PROVIDER_NAME": "ARTS UNIVERSITY BOURNEMOUTH, THE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 7,
      "STREET_NAME": "FERN BARROW",
      "LOCALITY": "",
      "TOWN": "POOLE",
      "COUNTY": "DORSET",
      "POSTCODE": "BH12 5HH",
      "WEBSITE_ADDRESS": "www.aub.ac.uk"
    },
    {
      "UKPRN": 10000571,
      "PROVIDER_NAME": "BATH SPA UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "NEWTON PARK",
      "STREET_NAME": "",
      "LOCALITY": "NEWTON ST. LOE",
      "TOWN": "BATH",
      "COUNTY": "",
      "POSTCODE": "BA2 9BN",
      "WEBSITE_ADDRESS": "www.bathspa.ac.uk"
    },
    {
      "UKPRN": 10000712,
      "PROVIDER_NAME": "UNIVERSITY COLLEGE BIRMINGHAM",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "SUMMER ROW",
      "LOCALITY": "",
      "TOWN": "BIRMINGHAM",
      "COUNTY": "",
      "POSTCODE": "B3 1JB",
      "WEBSITE_ADDRESS": "www.ucb.ac.uk"
    },
    {
      "UKPRN": 10000824,
      "PROVIDER_NAME": "BOURNEMOUTH UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "POOLE HOUSE",
      "BUILDING_NAME_NUMBER": "TALBOT CAMPUS",
      "STREET_NAME": "FERN BARROW",
      "LOCALITY": "",
      "TOWN": "POOLE",
      "COUNTY": "DORSET",
      "POSTCODE": "BH12 5BB",
      "WEBSITE_ADDRESS": "www.bournemouth.ac.uk"
    },
    {
      "UKPRN": 10000886,
      "PROVIDER_NAME": "UNIVERSITY OF BRIGHTON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "MITHRAS HOUSE",
      "STREET_NAME": "LEWES ROAD",
      "LOCALITY": "",
      "TOWN": "BRIGHTON",
      "COUNTY": "",
      "POSTCODE": "BN2 4AT",
      "WEBSITE_ADDRESS": "www.brighton.ac.uk"
    },
    {
      "UKPRN": 10000961,
      "PROVIDER_NAME": "BRUNEL UNIVERSITY",
      "ALIAS_TEXT": "Brunel University London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "KINGSTON LANE",
      "LOCALITY": "",
      "TOWN": "UXBRIDGE",
      "COUNTY": "MIDDLESEX",
      "POSTCODE": "UB8 3PH",
      "WEBSITE_ADDRESS": "www.brunel.ac.uk"
    },
    {
      "UKPRN": 10000975,
      "PROVIDER_NAME": "BUCKINGHAMSHIRE NEW UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "HIGH WYCOMBE CAMPUS",
      "STREET_NAME": "QUEEN ALEXANDRA ROAD",
      "LOCALITY": "",
      "TOWN": "HIGH WYCOMBE",
      "COUNTY": "BUCKINGHAMSHIRE",
      "POSTCODE": "HP11 2JZ",
      "WEBSITE_ADDRESS": "www.bucks.ac.uk"
    },
    {
      "UKPRN": 10001143,
      "PROVIDER_NAME": "CANTERBURY CHRIST CHURCH UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "ST. GEORGES PLACE",
      "LOCALITY": "",
      "TOWN": "CANTERBURY",
      "COUNTY": "KENT",
      "POSTCODE": "CT1 1UT",
      "WEBSITE_ADDRESS": "www.canterbury.ac.uk"
    },
    {
      "UKPRN": 10001282,
      "PROVIDER_NAME": "NORTHUMBRIA UNIVERSITY NEWCASTLE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "ELLISON BUILDING",
      "STREET_NAME": "ELLISON ROAD",
      "LOCALITY": "",
      "TOWN": "Newcastle Upon Tyne",
      "COUNTY": "",
      "POSTCODE": "NE1 8ST",
      "WEBSITE_ADDRESS": "www.northumbria.ac.uk"
    },
    {
      "UKPRN": 10001478,
      "PROVIDER_NAME": "THE CITY UNIVERSITY",
      "ALIAS_TEXT": "City University London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "NORTHAMPTON SQUARE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "EC1V 0HB",
      "WEBSITE_ADDRESS": "www.city.ac.uk"
    },
    {
      "UKPRN": 10001653,
      "PROVIDER_NAME": "THE CONSERVATOIRE FOR DANCE AND DRAMA",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "TAVISTOCK HOUSE",
      "STREET_NAME": "TAVISTOCK SQUARE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1H 9JJ",
      "WEBSITE_ADDRESS": "www.cdd.ac.uk"
    },
    {
      "UKPRN": 10001726,
      "PROVIDER_NAME": "COVENTRY UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "PRIORY STREET",
      "LOCALITY": "",
      "TOWN": "COVENTRY",
      "COUNTY": "",
      "POSTCODE": "CV1 5FB",
      "WEBSITE_ADDRESS": "www.coventry.ac.uk"
    },
    {
      "UKPRN": 10001883,
      "PROVIDER_NAME": "DE MONTFORT UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "THE GATEWAY",
      "LOCALITY": "",
      "TOWN": "LEICESTER",
      "COUNTY": "",
      "POSTCODE": "LE1 9BH",
      "WEBSITE_ADDRESS": "www.dmu.ac.uk"
    },
    {
      "UKPRN": 10002681,
      "PROVIDER_NAME": "GLASGOW SCHOOL OF ART.",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 167,
      "STREET_NAME": "RENFREW STREET",
      "LOCALITY": "",
      "TOWN": "GLASGOW",
      "COUNTY": "",
      "POSTCODE": "G3 6RQ",
      "WEBSITE_ADDRESS": "www.gsa.ac.uk"
    },
    {
      "UKPRN": 10002718,
      "PROVIDER_NAME": "GOLDSMITHS' COLLEGE",
      "ALIAS_TEXT": "Goldsmiths, University of London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "GOLDSMITHS COLLEGE 8",
      "STREET_NAME": "LEWISHAM WAY",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SE14 6NW",
      "WEBSITE_ADDRESS": "www.gold.ac.uk"
    },
    {
      "UKPRN": 10003270,
      "PROVIDER_NAME": "IMPERIAL COLLEGE OF SCIENCE, TECHNOLOGY AND MEDICINE",
      "ALIAS_TEXT": "Imperial College London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "FACULTY BUILDING",
      "STREET_NAME": "EXHIBITION ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SW7 2AZ",
      "WEBSITE_ADDRESS": "www.imperial.ac.uk"
    },
    {
      "UKPRN": 10003324,
      "PROVIDER_NAME": "INSTITUTE OF CANCER RESEARCH: ROYAL CANCER HOSPITAL (THE)",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 123,
      "STREET_NAME": "OLD BROMPTON ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SW7 3RP",
      "WEBSITE_ADDRESS": "www.icr.ac.uk"
    },
    {
      "UKPRN": 10003614,
      "PROVIDER_NAME": "UNIVERSITY OF WINCHESTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "SPARKFORD ROAD",
      "LOCALITY": "",
      "TOWN": "WINCHESTER",
      "COUNTY": "HAMPSHIRE",
      "POSTCODE": "SO22 4NR",
      "WEBSITE_ADDRESS": "www.winchester.ac.uk"
    },
    {
      "UKPRN": 10003645,
      "PROVIDER_NAME": "KING'S COLLEGE LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "STRAND",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC2R 2LS",
      "WEBSITE_ADDRESS": "www.kcl.ac.uk"
    },
    {
      "UKPRN": 10003678,
      "PROVIDER_NAME": "KINGSTON UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "RIVER HOUSE 53-57",
      "STREET_NAME": "HIGH STREET",
      "LOCALITY": "",
      "TOWN": "KINGSTON UPON THAMES",
      "COUNTY": "SURREY",
      "POSTCODE": "KT1 1LQ",
      "WEBSITE_ADDRESS": "www.kingston.ac.uk"
    },
    {
      "UKPRN": 10003854,
      "PROVIDER_NAME": "LEEDS COLLEGE OF ART",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "BLENHEIM WALK",
      "LOCALITY": "",
      "TOWN": "LEEDS",
      "COUNTY": "",
      "POSTCODE": "LS2 9AQ",
      "WEBSITE_ADDRESS": "www.leeds-art.ac.uk"
    },
    {
      "UKPRN": 10003861,
      "PROVIDER_NAME": "LEEDS METROPOLITAN UNIVERSITY",
      "ALIAS_TEXT": "Leeds Metropolitan University",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "CITY CAMPUS",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "LEEDS",
      "COUNTY": "",
      "POSTCODE": "LS1 3HE",
      "WEBSITE_ADDRESS": "www.leedsmet.ac.uk"
    },
    {
      "UKPRN": 10003863,
      "PROVIDER_NAME": "LEEDS TRINITY UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "BROWNBERRIE LANE",
      "LOCALITY": "HORSFORTH",
      "TOWN": "LEEDS",
      "COUNTY": "",
      "POSTCODE": "LS18 5HD",
      "WEBSITE_ADDRESS": "www.leedstrinity.ac.uk"
    },
    {
      "UKPRN": 10003945,
      "PROVIDER_NAME": "THE LIVERPOOL INSTITUTE FOR PERFORMING ARTS",
      "ALIAS_TEXT": "LIPA",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "Mount Street",
      "LOCALITY": "",
      "TOWN": "Liverpool",
      "COUNTY": "",
      "POSTCODE": "L1 9HF",
      "WEBSITE_ADDRESS": "www.lipa.ac.uk"
    },
    {
      "UKPRN": 10003956,
      "PROVIDER_NAME": "LIVERPOOL HOPE UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "HOPE PARK",
      "STREET_NAME": "TAGGART AVENUE",
      "LOCALITY": "",
      "TOWN": "LIVERPOOL",
      "COUNTY": "",
      "POSTCODE": "L16 9JD",
      "WEBSITE_ADDRESS": "www.hope.ac.uk"
    },
    {
      "UKPRN": 10003957,
      "PROVIDER_NAME": "LIVERPOOL JOHN MOORES UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "RODNEY HOUSE 70",
      "STREET_NAME": "MOUNT PLEASANT",
      "LOCALITY": "",
      "TOWN": "LIVERPOOL",
      "COUNTY": "",
      "POSTCODE": "L3 5UX",
      "WEBSITE_ADDRESS": "www.ljmu.ac.uk"
    },
    {
      "UKPRN": 10004048,
      "PROVIDER_NAME": "LONDON METROPOLITAN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "166-220",
      "STREET_NAME": "HOLLOWAY ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "N7 8DB",
      "WEBSITE_ADDRESS": "www.londonmet.ac.uk"
    },
    {
      "UKPRN": 10004063,
      "PROVIDER_NAME": "LONDON SCHOOL OF ECONOMICS & POLITICAL SCIENCE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "HOUGHTON STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC2A 2AE",
      "WEBSITE_ADDRESS": "www.lse.ac.uk"
    },
    {
      "UKPRN": 10004078,
      "PROVIDER_NAME": "LONDON SOUTH BANK UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 103,
      "STREET_NAME": "BOROUGH ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SE1 0AA",
      "WEBSITE_ADDRESS": "www.lsbu.ac.uk"
    },
    {
      "UKPRN": 10004113,
      "PROVIDER_NAME": "LOUGHBOROUGH UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "LOUGHBOROUGH",
      "COUNTY": "LEICESTERSHIRE",
      "POSTCODE": "LE11 3TU",
      "WEBSITE_ADDRESS": "www.lboro.ac.uk"
    },
    {
      "UKPRN": 10004180,
      "PROVIDER_NAME": "MANCHESTER METROPOLITAN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "ALL SAINTS",
      "STREET_NAME": "GROSVENOR SQUARE",
      "LOCALITY": "",
      "TOWN": "MANCHESTER",
      "COUNTY": "",
      "POSTCODE": "M15 6BH",
      "WEBSITE_ADDRESS": "www.mmu.ac.uk"
    },
    {
      "UKPRN": 10004351,
      "PROVIDER_NAME": "MIDDLESEX UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "THE BURROUGHS",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "NW4 4BT",
      "WEBSITE_ADDRESS": "www.mdx.ac.uk"
    },
    {
      "UKPRN": 10004775,
      "PROVIDER_NAME": "NORWICH UNIVERSITY OF THE ARTS",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 3,
      "STREET_NAME": "REDWELL STREET",
      "LOCALITY": "",
      "TOWN": "NORWICH",
      "COUNTY": "",
      "POSTCODE": "NR2 4SN",
      "WEBSITE_ADDRESS": "www.nua.ac.uk"
    },
    {
      "UKPRN": 10004797,
      "PROVIDER_NAME": "NOTTINGHAM TRENT UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "BURTON STREET",
      "LOCALITY": "",
      "TOWN": "NOTTINGHAM",
      "COUNTY": "",
      "POSTCODE": "NG1 4BU",
      "WEBSITE_ADDRESS": "www.ntu.ac.uk"
    },
    {
      "UKPRN": 10004930,
      "PROVIDER_NAME": "OXFORD BROOKES UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "GIPSY LANE",
      "LOCALITY": "HEADINGTON",
      "TOWN": "OXFORD",
      "COUNTY": "",
      "POSTCODE": "OX3 0BP",
      "WEBSITE_ADDRESS": "www.brookes.ac.uk"
    },
    {
      "UKPRN": 10005337,
      "PROVIDER_NAME": "QUEEN MARGARET UNIVERSITY, EDINBURGH",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "QUEEN MARGARET UNIVERSITY DRIVE",
      "LOCALITY": "",
      "TOWN": "MUSSELBURGH",
      "COUNTY": "",
      "POSTCODE": "EH21 6UU",
      "WEBSITE_ADDRESS": "www.qmu.ac.uk"
    },
    {
      "UKPRN": 10005343,
      "PROVIDER_NAME": "QUEEN'S UNIVERSITY OF BELFAST",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "UNIVERSITY ROAD",
      "LOCALITY": "",
      "TOWN": "BELFAST",
      "COUNTY": "",
      "POSTCODE": "BT7 1NN",
      "WEBSITE_ADDRESS": "www.qub.ac.uk"
    },
    {
      "UKPRN": 10005389,
      "PROVIDER_NAME": "RAVENSBOURNE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 6,
      "STREET_NAME": "PENROSE WAY",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SE10 0EW",
      "WEBSITE_ADDRESS": "www.rave.ac.uk"
    },
    {
      "UKPRN": 10005500,
      "PROVIDER_NAME": "THE ROBERT GORDON UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "CENTRAL SERVICES BUILDING",
      "STREET_NAME": "GARTHDEE ROAD",
      "LOCALITY": "",
      "TOWN": "ABERDEEN",
      "COUNTY": "",
      "POSTCODE": "AB10 7FY",
      "WEBSITE_ADDRESS": "www.rgu.ac.uk"
    },
    {
      "UKPRN": 10005523,
      "PROVIDER_NAME": "ROSE BRUFORD COLLEGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "Lamorbey Park Burnt Oak Lane",
      "LOCALITY": "",
      "TOWN": "Sidcup",
      "COUNTY": "Kent",
      "POSTCODE": "DA15 9DF",
      "WEBSITE_ADDRESS": "www.bruford.ac.uk"
    },
    {
      "UKPRN": 10005545,
      "PROVIDER_NAME": "ROYAL AGRICULTURAL UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "Stroud Road",
      "LOCALITY": "",
      "TOWN": "Cirencester",
      "COUNTY": "Gloucestershire",
      "POSTCODE": "GL7 6JS",
      "WEBSITE_ADDRESS": "www.rac.ac.uk"
    },
    {
      "UKPRN": 10005553,
      "PROVIDER_NAME": "ROYAL HOLLOWAY COLLEGE AND BEDFORD NEW COLLEGE",
      "ALIAS_TEXT": "Royal Holloway, University of London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "EGHAM HILL",
      "LOCALITY": "",
      "TOWN": "EGHAM",
      "COUNTY": "",
      "POSTCODE": "TW20 0EX",
      "WEBSITE_ADDRESS": "www.rhul.ac.uk"
    },
    {
      "UKPRN": 10005561,
      "PROVIDER_NAME": "ROYAL CONSERVATOIRE OF SCOTLAND",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 100,
      "STREET_NAME": "RENFREW STREET",
      "LOCALITY": "",
      "TOWN": "GLASGOW",
      "COUNTY": "",
      "POSTCODE": "G2 3DB",
      "WEBSITE_ADDRESS": "www.rcs.ac.uk"
    },
    {
      "UKPRN": 10005700,
      "PROVIDER_NAME": "SRUC",
      "ALIAS_TEXT": "Scotland's Rural College",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "KING'S BUILDINGS WEST MAINS ROAD",
      "LOCALITY": "",
      "TOWN": "EDINBURGH",
      "COUNTY": "",
      "POSTCODE": "EH9 3JG",
      "WEBSITE_ADDRESS": "www.sruc.ac.uk"
    },
    {
      "UKPRN": 10005790,
      "PROVIDER_NAME": "SHEFFIELD HALLAM UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "CITY CAMPUS",
      "STREET_NAME": "POND STREET",
      "LOCALITY": "",
      "TOWN": "SHEFFIELD",
      "COUNTY": "",
      "POSTCODE": "S1 1WB",
      "WEBSITE_ADDRESS": "www.shu.ac.uk"
    },
    {
      "UKPRN": 10006022,
      "PROVIDER_NAME": "SOUTHAMPTON SOLENT UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "EAST PARK TERRACE",
      "LOCALITY": "",
      "TOWN": "SOUTHAMPTON",
      "COUNTY": "",
      "POSTCODE": "SO14 0YN",
      "WEBSITE_ADDRESS": "www.solent.ac.uk"
    },
    {
      "UKPRN": 10006299,
      "PROVIDER_NAME": "STAFFORDSHIRE UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "COLLEGE ROAD",
      "LOCALITY": "",
      "TOWN": "STOKE-ON-TRENT",
      "COUNTY": "",
      "POSTCODE": "ST4 2DE",
      "WEBSITE_ADDRESS": "www.staffs.ac.uk"
    },
    {
      "UKPRN": 10006427,
      "PROVIDER_NAME": "UNIVERSITY FOR THE CREATIVE ARTS",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "FALKNER ROAD",
      "LOCALITY": "",
      "TOWN": "FARNHAM",
      "COUNTY": "SURREY",
      "POSTCODE": "GU9 7DS",
      "WEBSITE_ADDRESS": "www.ucreative.ac.uk"
    },
    {
      "UKPRN": 10006566,
      "PROVIDER_NAME": "UNIVERSITY OF WEST LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "ST. MARYS ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "W5 5RF",
      "WEBSITE_ADDRESS": "www.uwl.ac.uk"
    },
    {
      "UKPRN": 10006840,
      "PROVIDER_NAME": "UNIVERSITY OF BIRMINGHAM",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "EDGBASTON",
      "TOWN": "BIRMINGHAM",
      "COUNTY": "",
      "POSTCODE": "B15 2TT",
      "WEBSITE_ADDRESS": "www.birmingham.ac.uk"
    },
    {
      "UKPRN": 10006841,
      "PROVIDER_NAME": "UNIVERSITY OF BOLTON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "DEANE ROAD",
      "LOCALITY": "",
      "TOWN": "BOLTON",
      "COUNTY": "",
      "POSTCODE": "BL3 5AB",
      "WEBSITE_ADDRESS": "www.bolton.ac.uk"
    },
    {
      "UKPRN": 10006842,
      "PROVIDER_NAME": "UNIVERSITY OF LIVERPOOL",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "PO Box 147",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "LIVERPOOL",
      "COUNTY": "",
      "POSTCODE": "L69 3BX",
      "WEBSITE_ADDRESS": "www.liv.ac.uk"
    },
    {
      "UKPRN": 10007114,
      "PROVIDER_NAME": "UNIVERSITY OF THE HIGHLANDS AND ISLANDS",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "12b",
      "STREET_NAME": "Ness Walk",
      "LOCALITY": "",
      "TOWN": "Inverness",
      "COUNTY": "",
      "POSTCODE": "IV3 5SQ",
      "WEBSITE_ADDRESS": "www.uhi.ac.uk"
    },
    {
      "UKPRN": 10007137,
      "PROVIDER_NAME": "THE UNIVERSITY OF CHICHESTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "BISHOP OTTER CAMPUS",
      "STREET_NAME": "COLLEGE LANE",
      "LOCALITY": "",
      "TOWN": "CHICHESTER",
      "COUNTY": "WEST SUSSEX",
      "POSTCODE": "PO19 6PE",
      "WEBSITE_ADDRESS": "www.chi.ac.uk"
    },
    {
      "UKPRN": 10007138,
      "PROVIDER_NAME": "UNIVERSITY OF NORTHAMPTON,THE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "BOUGHTON GREEN ROAD",
      "LOCALITY": "",
      "TOWN": "NORTHAMPTON",
      "COUNTY": "",
      "POSTCODE": "NN2 7AL",
      "WEBSITE_ADDRESS": "www.northampton.ac.uk"
    },
    {
      "UKPRN": 10007139,
      "PROVIDER_NAME": "UNIVERSITY OF WORCESTER, THE",
      "ALIAS_TEXT": "University of Worcester",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "HENWICK GROVE",
      "LOCALITY": "",
      "TOWN": "WORCESTER",
      "COUNTY": "",
      "POSTCODE": "WR2 6AJ",
      "WEBSITE_ADDRESS": "www.worc.ac.uk"
    },
    {
      "UKPRN": 10007140,
      "PROVIDER_NAME": "BIRMINGHAM CITY UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "FRANCHISE STREET",
      "LOCALITY": "PERRY BARR",
      "TOWN": "BIRMINGHAM",
      "COUNTY": "",
      "POSTCODE": "B42 2SU",
      "WEBSITE_ADDRESS": "www.bcu.ac.uk"
    },
    {
      "UKPRN": 10007141,
      "PROVIDER_NAME": "UNIVERSITY OF CENTRAL LANCASHIRE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "PRESTON",
      "COUNTY": "",
      "POSTCODE": "PR1 2HE",
      "WEBSITE_ADDRESS": "www.uclan.ac.uk"
    },
    {
      "UKPRN": 10007143,
      "PROVIDER_NAME": "UNIVERSITY OF DURHAM",
      "ALIAS_TEXT": "Durham University",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "PALATINE CENTRE",
      "STREET_NAME": "STOCKTON ROAD",
      "LOCALITY": "",
      "TOWN": "DURHAM",
      "COUNTY": "",
      "POSTCODE": "DH1 3LE",
      "WEBSITE_ADDRESS": "www.dur.ac.uk"
    },
    {
      "UKPRN": 10007144,
      "PROVIDER_NAME": "UNIVERSITY OF EAST LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "EAST BUILDING 4",
      "STREET_NAME": "UNIVERSITY WAY",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "E16 2RD",
      "WEBSITE_ADDRESS": "www.uel.ac.uk"
    },
    {
      "UKPRN": 10007145,
      "PROVIDER_NAME": "UNIVERSITY OF GLOUCESTERSHIRE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "The Park",
      "LOCALITY": "",
      "TOWN": "Cheltenham",
      "COUNTY": "Gloucestershire",
      "POSTCODE": "GL50 2RH",
      "WEBSITE_ADDRESS": "www.glos.ac.uk"
    },
    {
      "UKPRN": 10007146,
      "PROVIDER_NAME": "UNIVERSITY OF GREENWICH",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 30,
      "STREET_NAME": "Park Row",
      "LOCALITY": "",
      "TOWN": "London",
      "COUNTY": "",
      "POSTCODE": "SE10 9LS",
      "WEBSITE_ADDRESS": "www.greenwich.ac.uk"
    },
    {
      "UKPRN": 10007147,
      "PROVIDER_NAME": "UNIVERSITY OF HERTFORDSHIRE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "COLLEGE LANE",
      "LOCALITY": "",
      "TOWN": "HATFIELD",
      "COUNTY": "HERTFORDSHIRE",
      "POSTCODE": "AL10 9AB",
      "WEBSITE_ADDRESS": "www.herts.ac.uk"
    },
    {
      "UKPRN": 10007148,
      "PROVIDER_NAME": "UNIVERSITY OF HUDDERSFIELD",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "QUEENSGATE",
      "LOCALITY": "",
      "TOWN": "HUDDERSFIELD",
      "COUNTY": "",
      "POSTCODE": "HD1 3DH",
      "WEBSITE_ADDRESS": "www.hud.ac.uk"
    },
    {
      "UKPRN": 10007149,
      "PROVIDER_NAME": "UNIVERSITY OF HULL",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "COTTINGHAM ROAD",
      "LOCALITY": "",
      "TOWN": "HULL",
      "COUNTY": "",
      "POSTCODE": "HU6 7RX",
      "WEBSITE_ADDRESS": "www.hull.ac.uk"
    },
    {
      "UKPRN": 10007150,
      "PROVIDER_NAME": "UNIVERSITY OF KENT",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "THE REGISTRY",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "CANTERBURY",
      "COUNTY": "KENT",
      "POSTCODE": "CT2 7NZ",
      "WEBSITE_ADDRESS": "www.kent.ac.uk"
    },
    {
      "UKPRN": 10007151,
      "PROVIDER_NAME": "UNIVERSITY OF LINCOLN",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "CAMPUS WAY",
      "LOCALITY": "",
      "TOWN": "LINCOLN",
      "COUNTY": "",
      "POSTCODE": "LN6 7TS",
      "WEBSITE_ADDRESS": "www.lincoln.ac.uk"
    },
    {
      "UKPRN": 10007152,
      "PROVIDER_NAME": "UNIVERSITY OF BEDFORDSHIRE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "UNIVERSITY SQUARE",
      "LOCALITY": "",
      "TOWN": "LUTON",
      "COUNTY": "",
      "POSTCODE": "LU1 3JU",
      "WEBSITE_ADDRESS": "www.beds.ac.uk"
    },
    {
      "UKPRN": 10007154,
      "PROVIDER_NAME": "UNIVERSITY OF NOTTINGHAM, THE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "UNIVERSITY PARK",
      "LOCALITY": "",
      "TOWN": "NOTTINGHAM",
      "COUNTY": "",
      "POSTCODE": "NG7 2RD",
      "WEBSITE_ADDRESS": "www.nottingham.ac.uk"
    },
    {
      "UKPRN": 10007155,
      "PROVIDER_NAME": "UNIVERSITY OF PORTSMOUTH",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "UNIVERSITY HOUSE",
      "STREET_NAME": "WINSTON CHURCHILL AVENUE",
      "LOCALITY": "",
      "TOWN": "PORTSMOUTH",
      "COUNTY": "",
      "POSTCODE": "PO1 2UP",
      "WEBSITE_ADDRESS": "www.port.ac.uk"
    },
    {
      "UKPRN": 10007156,
      "PROVIDER_NAME": "UNIVERSITY OF SALFORD, THE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "FARADAY HOUSE 43",
      "STREET_NAME": "CRESCENT",
      "LOCALITY": "",
      "TOWN": "SALFORD",
      "COUNTY": "",
      "POSTCODE": "M5 4WT",
      "WEBSITE_ADDRESS": "www.salford.ac.uk"
    },
    {
      "UKPRN": 10007157,
      "PROVIDER_NAME": "UNIVERSITY OF SHEFFIELD",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "WESTERN BANK",
      "LOCALITY": "",
      "TOWN": "SHEFFIELD",
      "COUNTY": "",
      "POSTCODE": "S10 2TN",
      "WEBSITE_ADDRESS": "www.shef.ac.uk"
    },
    {
      "UKPRN": 10007158,
      "PROVIDER_NAME": "UNIVERSITY OF SOUTHAMPTON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "UNIVERSITY ROAD",
      "LOCALITY": "",
      "TOWN": "SOUTHAMPTON",
      "COUNTY": "",
      "POSTCODE": "SO17 1BJ",
      "WEBSITE_ADDRESS": "www.soton.ac.uk"
    },
    {
      "UKPRN": 10007159,
      "PROVIDER_NAME": "UNIVERSITY OF SUNDERLAND",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "CHESTER ROAD",
      "LOCALITY": "",
      "TOWN": "SUNDERLAND",
      "COUNTY": "",
      "POSTCODE": "SR1 3SD",
      "WEBSITE_ADDRESS": "www.sunderland.ac.uk"
    },
    {
      "UKPRN": 10007160,
      "PROVIDER_NAME": "UNIVERSITY OF SURREY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "GUILDFORD",
      "COUNTY": "SURREY",
      "POSTCODE": "GU2 7XH",
      "WEBSITE_ADDRESS": "www.surrey.ac.uk"
    },
    {
      "UKPRN": 10007161,
      "PROVIDER_NAME": "TEESSIDE UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "BOROUGH ROAD",
      "LOCALITY": "",
      "TOWN": "MIDDLESBROUGH",
      "COUNTY": "CLEVELAND",
      "POSTCODE": "TS1 3BA",
      "WEBSITE_ADDRESS": "www.tees.ac.uk"
    },
    {
      "UKPRN": 10007162,
      "PROVIDER_NAME": "UNIVERSITY OF THE ARTS, LONDON",
      "ALIAS_TEXT": "University of the Arts London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 272,
      "STREET_NAME": "HIGH HOLBORN",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1V 7EY",
      "WEBSITE_ADDRESS": "www.arts.ac.uk"
    },
    {
      "UKPRN": 10007163,
      "PROVIDER_NAME": "UNIVERSITY OF WARWICK",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "UNIVERSITY HOUSE",
      "STREET_NAME": "GIBBET HILL ROAD",
      "LOCALITY": "",
      "TOWN": "COVENTRY",
      "COUNTY": "",
      "POSTCODE": "CV4 7AL",
      "WEBSITE_ADDRESS": "www.warwick.ac.uk"
    },
    {
      "UKPRN": 10007164,
      "PROVIDER_NAME": "UNIVERSITY OF THE WEST OF ENGLAND, BRISTOL",
      "ALIAS_TEXT": "UWE",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "FRENCHAY CAMPUS",
      "STREET_NAME": "COLDHARBOUR LANE",
      "LOCALITY": "",
      "TOWN": "BRISTOL",
      "COUNTY": "",
      "POSTCODE": "BS16 1QY",
      "WEBSITE_ADDRESS": "www.uwe.ac.uk"
    },
    {
      "UKPRN": 10007165,
      "PROVIDER_NAME": "THE UNIVERSITY OF WESTMINSTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 309,
      "STREET_NAME": "REGENT STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "W1B 2HW",
      "WEBSITE_ADDRESS": "www.westminster.ac.uk"
    },
    {
      "UKPRN": 10007166,
      "PROVIDER_NAME": "UNIVERSITY OF WOLVERHAMPTON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "WULFRUNA STREET",
      "LOCALITY": "",
      "TOWN": "WOLVERHAMPTON",
      "COUNTY": "",
      "POSTCODE": "WV1 1LY",
      "WEBSITE_ADDRESS": "www.wlv.ac.uk"
    },
    {
      "UKPRN": 10007167,
      "PROVIDER_NAME": "UNIVERSITY OF YORK",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "HESLINGTON",
      "TOWN": "YORK",
      "COUNTY": "",
      "POSTCODE": "YO10 5DD",
      "WEBSITE_ADDRESS": "www.york.ac.uk"
    },
    {
      "UKPRN": 10007657,
      "PROVIDER_NAME": "WRITTLE COLLEGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "LORDSHIP ROAD",
      "LOCALITY": "WRITTLE",
      "TOWN": "CHELMSFORD",
      "COUNTY": "",
      "POSTCODE": "CM1 3RR",
      "WEBSITE_ADDRESS": "www.writtle.ac.uk"
    },
    {
      "UKPRN": 10007713,
      "PROVIDER_NAME": "YORK ST JOHN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "LORD MAYORS WALK",
      "LOCALITY": "",
      "TOWN": "YORK",
      "COUNTY": "",
      "POSTCODE": "YO31 7EX",
      "WEBSITE_ADDRESS": "www.yorksj.ac.uk"
    },
    {
      "UKPRN": 10007759,
      "PROVIDER_NAME": "ASTON UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "THE ASTON TRIANGLE",
      "LOCALITY": "",
      "TOWN": "BIRMINGHAM",
      "COUNTY": "",
      "POSTCODE": "B4 7ET",
      "WEBSITE_ADDRESS": "www.aston.ac.uk"
    },
    {
      "UKPRN": 10007760,
      "PROVIDER_NAME": "BIRKBECK COLLEGE",
      "ALIAS_TEXT": "Birkbeck, University Of London",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "BIRKBECK COLLEGE",
      "STREET_NAME": "MALET STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1E 7HX",
      "WEBSITE_ADDRESS": "www.bbk.ac.uk"
    },
    {
      "UKPRN": 10007761,
      "PROVIDER_NAME": "COURTAULD INSTITUTE OF ART",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "SOMERSET HOUSE",
      "STREET_NAME": "STRAND",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC2R 0RN",
      "WEBSITE_ADDRESS": "www.courtauld.ac.uk"
    },
    {
      "UKPRN": 10007762,
      "PROVIDER_NAME": "GLASGOW CALEDONIAN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "CITY CAMPUS 70",
      "STREET_NAME": "COWCADDENS ROAD",
      "LOCALITY": "",
      "TOWN": "GLASGOW",
      "COUNTY": "",
      "POSTCODE": "G4 0BA",
      "WEBSITE_ADDRESS": "www.gcu.ac.uk"
    },
    {
      "UKPRN": 10007764,
      "PROVIDER_NAME": "HERIOT-WATT UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "RICCARTON",
      "TOWN": "CURRIE",
      "COUNTY": "MIDLOTHIAN",
      "POSTCODE": "EH14 4AS",
      "WEBSITE_ADDRESS": "www.hw.ac.uk"
    },
    {
      "UKPRN": 10007765,
      "PROVIDER_NAME": "HEYTHROP COLLEGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 23,
      "STREET_NAME": "KENSINGTON SQUARE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "W8 5HN",
      "WEBSITE_ADDRESS": "www.heythrop.ac.uk"
    },
    {
      "UKPRN": 10007766,
      "PROVIDER_NAME": "INSTITUTE OF EDUCATION, UNIVERSITY OF LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 20,
      "STREET_NAME": "BEDFORD WAY",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1H 0AL",
      "WEBSITE_ADDRESS": "www.ioe.ac.uk"
    },
    {
      "UKPRN": 10007767,
      "PROVIDER_NAME": "UNIVERSITY OF KEELE",
      "ALIAS_TEXT": "Keele University",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "KEELE",
      "TOWN": "NEWCASTLE",
      "COUNTY": "",
      "POSTCODE": "ST5 5BG",
      "WEBSITE_ADDRESS": "www.keele.ac.uk"
    },
    {
      "UKPRN": 10007768,
      "PROVIDER_NAME": "UNIVERSITY OF LANCASTER",
      "ALIAS_TEXT": "Lancaster University",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "UNIVERSITY HOUSE",
      "STREET_NAME": "",
      "LOCALITY": "BAILRIGG",
      "TOWN": "LANCASTER",
      "COUNTY": "",
      "POSTCODE": "LA1 4YW",
      "WEBSITE_ADDRESS": "www.lancs.ac.uk"
    },
    {
      "UKPRN": 10007769,
      "PROVIDER_NAME": "LONDON BUSINESS SCHOOL",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "SUSSEX PLACE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "NW1 4SA",
      "WEBSITE_ADDRESS": "www.london.edu"
    },
    {
      "UKPRN": 10007771,
      "PROVIDER_NAME": "LONDON SCHOOL OF HYGIENE AND TROPICAL MEDICINE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "KEPPEL STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1E 7HT",
      "WEBSITE_ADDRESS": "www.lshtm.ac.uk"
    },
    {
      "UKPRN": 10007772,
      "PROVIDER_NAME": "EDINBURGH NAPIER UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "SIGHTHILL CAMPUS 9",
      "STREET_NAME": "SIGHTHILL COURT",
      "LOCALITY": "",
      "TOWN": "EDINBURGH",
      "COUNTY": "",
      "POSTCODE": "EH11 4BN",
      "WEBSITE_ADDRESS": "www.napier.ac.uk"
    },
    {
      "UKPRN": 10007773,
      "PROVIDER_NAME": "OPEN UNIVERSITY(THE)",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "WALTON HALL",
      "TOWN": "MILTON KEYNES",
      "COUNTY": "",
      "POSTCODE": "MK7 6AA",
      "WEBSITE_ADDRESS": "www.open.ac.uk"
    },
    {
      "UKPRN": 10007774,
      "PROVIDER_NAME": "UNIVERSITY OF OXFORD",
      "ALIAS_TEXT": "Oxford University",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "UNIVERSITY OFFICES",
      "STREET_NAME": "WELLINGTON SQUARE",
      "LOCALITY": "",
      "TOWN": "OXFORD",
      "COUNTY": "",
      "POSTCODE": "OX1 2JD",
      "WEBSITE_ADDRESS": "www.ox.ac.uk"
    },
    {
      "UKPRN": 10007775,
      "PROVIDER_NAME": "QUEEN MARY UNIVERSITY OF LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 327,
      "STREET_NAME": "MILE END ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "E1 4NS",
      "WEBSITE_ADDRESS": "www.qmul.ac.uk"
    },
    {
      "UKPRN": 10007776,
      "PROVIDER_NAME": "ROEHAMPTON UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "ERASMUS HOUSE",
      "STREET_NAME": "ROEHAMPTON LANE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SW15 5PJ",
      "WEBSITE_ADDRESS": "www.roehampton.ac.uk"
    },
    {
      "UKPRN": 10007777,
      "PROVIDER_NAME": "ROYAL COLLEGE OF ART(THE)",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "KENSINGTON GORE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SW7 2EU",
      "WEBSITE_ADDRESS": "www.rca.ac.uk"
    },
    {
      "UKPRN": 10007778,
      "PROVIDER_NAME": "ROYAL COLLEGE OF MUSIC",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "PRINCE CONSORT ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SW7 2BS",
      "WEBSITE_ADDRESS": "www.rcm.ac.uk"
    },
    {
      "UKPRN": 10007779,
      "PROVIDER_NAME": "THE ROYAL VETERINARY COLLEGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "ROYAL COLLEGE STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "NW1 0TU",
      "WEBSITE_ADDRESS": "www.rvc.ac.uk"
    },
    {
      "UKPRN": 10007780,
      "PROVIDER_NAME": "SCHOOL OF ORIENTAL AND AFRICAN STUDIES",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 10,
      "STREET_NAME": "THORNHAUGH STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1H 0XG",
      "WEBSITE_ADDRESS": "www.soas.ac.uk"
    },
    {
      "UKPRN": 10007781,
      "PROVIDER_NAME": "SCHOOL OF PHARMACY UNIVERSITY OF LONDON(THE)",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "29-39",
      "STREET_NAME": "BRUNSWICK SQUARE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1N 1AX",
      "WEBSITE_ADDRESS": "www.pharmacy.ac.uk"
    },
    {
      "UKPRN": 10007782,
      "PROVIDER_NAME": "ST. GEORGE'S, UNIVERSITY OF LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "CRANMER TERRACE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SW17 0RE",
      "WEBSITE_ADDRESS": "www.sgul.ac.uk"
    },
    {
      "UKPRN": 10007783,
      "PROVIDER_NAME": "UNIVERSITY OF ABERDEEN",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "REGENT WALK",
      "LOCALITY": "",
      "TOWN": "ABERDEEN",
      "COUNTY": "",
      "POSTCODE": "AB24 3FX",
      "WEBSITE_ADDRESS": "www.abdn.ac.uk"
    },
    {
      "UKPRN": 10007784,
      "PROVIDER_NAME": "UNIVERSITY COLLEGE LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "GOWER STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1E 6BT",
      "WEBSITE_ADDRESS": "www.ucl.ac.uk"
    },
    {
      "UKPRN": 10007785,
      "PROVIDER_NAME": "UNIVERSITY OF BRADFORD",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "RICHMOND ROAD",
      "LOCALITY": "",
      "TOWN": "BRADFORD",
      "COUNTY": "WEST YORKSHIRE",
      "POSTCODE": "BD7 1DP",
      "WEBSITE_ADDRESS": "www.bradford.ac.uk"
    },
    {
      "UKPRN": 10007786,
      "PROVIDER_NAME": "UNIVERSITY OF BRISTOL",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "SENATE HOUSE",
      "STREET_NAME": "TYNDALL AVENUE",
      "LOCALITY": "",
      "TOWN": "BRISTOL",
      "COUNTY": "",
      "POSTCODE": "BS8 1TH",
      "WEBSITE_ADDRESS": "www.bristol.ac.uk"
    },
    {
      "UKPRN": 10007787,
      "PROVIDER_NAME": "THE UNIVERSITY OF BUCKINGHAM",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "YEOMANRY HOUSE",
      "STREET_NAME": "HUNTER STREET",
      "LOCALITY": "",
      "TOWN": "BUCKINGHAM",
      "COUNTY": "",
      "POSTCODE": "MK18 1EG",
      "WEBSITE_ADDRESS": "www.buckingham.ac.uk"
    },
    {
      "UKPRN": 10007788,
      "PROVIDER_NAME": "UNIVERSITY OF CAMBRIDGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "THE OLD SCHOOL",
      "STREET_NAME": "TRINITY LANE",
      "LOCALITY": "",
      "TOWN": "CAMBRIDGE",
      "COUNTY": "",
      "POSTCODE": "CB2 1TN",
      "WEBSITE_ADDRESS": "www.cam.ac.uk"
    },
    {
      "UKPRN": 10007789,
      "PROVIDER_NAME": "UNIVERSITY OF EAST ANGLIA",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "NORWICH RESEARCH PARK",
      "STREET_NAME": "EARLHAM ROAD",
      "LOCALITY": "",
      "TOWN": "NORWICH",
      "COUNTY": "",
      "POSTCODE": "NR4 7TJ",
      "WEBSITE_ADDRESS": "www.uea.ac.uk"
    },
    {
      "UKPRN": 10007790,
      "PROVIDER_NAME": "UNIVERSITY OF EDINBURGH",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "9-15",
      "STREET_NAME": "CHAMBERS STREET",
      "LOCALITY": "",
      "TOWN": "EDINBURGH",
      "COUNTY": "",
      "POSTCODE": "EH1 1HT",
      "WEBSITE_ADDRESS": "www.ed.ac.uk"
    },
    {
      "UKPRN": 10007791,
      "PROVIDER_NAME": "UNIVERSITY OF ESSEX",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "WIVENHOE PARK",
      "LOCALITY": "",
      "TOWN": "COLCHESTER",
      "COUNTY": "",
      "POSTCODE": "CO4 3SQ",
      "WEBSITE_ADDRESS": "www.essex.ac.uk"
    },
    {
      "UKPRN": 10007792,
      "PROVIDER_NAME": "UNIVERSITY OF EXETER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "STOCKER ROAD",
      "LOCALITY": "",
      "TOWN": "EXETER",
      "COUNTY": "",
      "POSTCODE": "EX4 4PY",
      "WEBSITE_ADDRESS": "www.exeter.ac.uk"
    },
    {
      "UKPRN": 10007793,
      "PROVIDER_NAME": "UNIVERSITY OF SOUTH WALES/PRIFYSGOL DE CYMRU",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "TREFOREST",
      "TOWN": "PONTYPRIDD",
      "COUNTY": "MID GLAMORGAN",
      "POSTCODE": "CF37 1DL",
      "WEBSITE_ADDRESS": "www.southwales.ac.uk"
    },
    {
      "UKPRN": 10007794,
      "PROVIDER_NAME": "UNIVERSITY OF GLASGOW",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "UNIVERSITY AVENUE",
      "LOCALITY": "",
      "TOWN": "GLASGOW",
      "COUNTY": "",
      "POSTCODE": "G12 8QQ",
      "WEBSITE_ADDRESS": "www.gla.ac.uk"
    },
    {
      "UKPRN": 10007795,
      "PROVIDER_NAME": "UNIVERSITY OF LEEDS",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "WOODHOUSE LANE",
      "LOCALITY": "",
      "TOWN": "LEEDS",
      "COUNTY": "",
      "POSTCODE": "LS2 9JT",
      "WEBSITE_ADDRESS": "www.leeds.ac.uk"
    },
    {
      "UKPRN": 10007796,
      "PROVIDER_NAME": "UNIVERSITY OF LEICESTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "UNIVERSITY ROAD",
      "LOCALITY": "",
      "TOWN": "LEICESTER",
      "COUNTY": "",
      "POSTCODE": "LE1 7RH",
      "WEBSITE_ADDRESS": "www.le.ac.uk"
    },
    {
      "UKPRN": 10007797,
      "PROVIDER_NAME": "UNIVERSITY OF LONDON",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "SENATE HOUSE",
      "STREET_NAME": "MALET STREET",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "WC1E 7HU",
      "WEBSITE_ADDRESS": "www.lon.ac.uk"
    },
    {
      "UKPRN": 10007798,
      "PROVIDER_NAME": "THE UNIVERSITY OF MANCHESTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "OXFORD ROAD",
      "LOCALITY": "",
      "TOWN": "MANCHESTER",
      "COUNTY": "",
      "POSTCODE": "M13 9PL",
      "WEBSITE_ADDRESS": "www.manchester.ac.uk"
    },
    {
      "UKPRN": 10007799,
      "PROVIDER_NAME": "NEWCASTLE UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "CLAREMONT ROAD",
      "LOCALITY": "",
      "TOWN": "NEWCASTLE UPON TYNE",
      "COUNTY": "",
      "POSTCODE": "NE1 7RU",
      "WEBSITE_ADDRESS": "www.ncl.ac.uk"
    },
    {
      "UKPRN": 10007800,
      "PROVIDER_NAME": "UNIVERSITY OF THE WEST OF SCOTLAND",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "HIGH STREET",
      "LOCALITY": "",
      "TOWN": "PAISLEY",
      "COUNTY": "RENFREWSHIRE",
      "POSTCODE": "PA1 2BE",
      "WEBSITE_ADDRESS": "www.uws.ac.uk"
    },
    {
      "UKPRN": 10007801,
      "PROVIDER_NAME": "PLYMOUTH UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "DRAKE CIRCUS",
      "LOCALITY": "",
      "TOWN": "PLYMOUTH",
      "COUNTY": "",
      "POSTCODE": "PL4 8AA",
      "WEBSITE_ADDRESS": "www.plymouth.ac.uk"
    },
    {
      "UKPRN": 10007802,
      "PROVIDER_NAME": "UNIVERSITY OF READING",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "WHITEKNIGHTS HOUSE",
      "STREET_NAME": "",
      "LOCALITY": "WHITEKNIGHTS",
      "TOWN": "READING",
      "COUNTY": "",
      "POSTCODE": "RG6 6UR",
      "WEBSITE_ADDRESS": "www.reading.ac.uk"
    },
    {
      "UKPRN": 10007803,
      "PROVIDER_NAME": "UNIVERSITY OF ST ANDREWS",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "COLLEGE GATE",
      "STREET_NAME": "NORTH STREET",
      "LOCALITY": "",
      "TOWN": "ST. ANDREWS",
      "COUNTY": "",
      "POSTCODE": "KY16 9AJ",
      "WEBSITE_ADDRESS": "www.st-andrews.ac.uk"
    },
    {
      "UKPRN": 10007804,
      "PROVIDER_NAME": "UNIVERSITY OF STIRLING",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "STIRLING",
      "COUNTY": "",
      "POSTCODE": "FK9 4LA",
      "WEBSITE_ADDRESS": "www.stir.ac.uk"
    },
    {
      "UKPRN": 10007805,
      "PROVIDER_NAME": "UNIVERSITY OF STRATHCLYDE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "MCCANCE BUILDING 16",
      "STREET_NAME": "RICHMOND STREET",
      "LOCALITY": "",
      "TOWN": "GLASGOW",
      "COUNTY": "",
      "POSTCODE": "G1 1XQ",
      "WEBSITE_ADDRESS": "www.strath.ac.uk"
    },
    {
      "UKPRN": 10007806,
      "PROVIDER_NAME": "UNIVERSITY OF SUSSEX",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "SUSSEX HOUSE",
      "STREET_NAME": "SOUTHERN RING ROAD",
      "LOCALITY": "FALMER",
      "TOWN": "BRIGHTON",
      "COUNTY": "",
      "POSTCODE": "BN1 9RH",
      "WEBSITE_ADDRESS": "www.sussex.ac.uk"
    },
    {
      "UKPRN": 10007807,
      "PROVIDER_NAME": "UNIVERSITY OF ULSTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "CROMORE ROAD",
      "LOCALITY": "",
      "TOWN": "COLERAINE",
      "COUNTY": "COUNTY LONDONDERRY",
      "POSTCODE": "BT52 1SA",
      "WEBSITE_ADDRESS": "www.ulster.ac.uk"
    },
    {
      "UKPRN": 10007811,
      "PROVIDER_NAME": "BISHOP GROSSETESTE UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "LONGDALES ROAD",
      "LOCALITY": "",
      "TOWN": "LINCOLN",
      "COUNTY": "",
      "POSTCODE": "LN1 3DY",
      "WEBSITE_ADDRESS": "www.bishopg.ac.uk"
    },
    {
      "UKPRN": 10007814,
      "PROVIDER_NAME": "CARDIFF UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "PARK PLACE",
      "LOCALITY": "",
      "TOWN": "CARDIFF",
      "COUNTY": "",
      "POSTCODE": "CF10 3AT",
      "WEBSITE_ADDRESS": "www.cardiff.ac.uk"
    },
    {
      "UKPRN": 10007816,
      "PROVIDER_NAME": "THE ROYAL CENTRAL SCHOOL OF SPEECH AND DRAMA",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "EMBASSY THEATRE 62-64",
      "STREET_NAME": "ETON AVENUE",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "NW3 3HY",
      "WEBSITE_ADDRESS": "www.cssd.ac.uk"
    },
    {
      "UKPRN": 10007822,
      "PROVIDER_NAME": "CRANFIELD UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "COLLEGE ROAD",
      "LOCALITY": "CRANFIELD",
      "TOWN": "BEDFORD",
      "COUNTY": "",
      "POSTCODE": "MK43 0AL",
      "WEBSITE_ADDRESS": "www.cranfield.ac.uk"
    },
    {
      "UKPRN": 10007823,
      "PROVIDER_NAME": "EDGE HILL UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "ST. HELENS ROAD",
      "LOCALITY": "",
      "TOWN": "ORMSKIRK",
      "COUNTY": "LANCASHIRE",
      "POSTCODE": "L39 4QP",
      "WEBSITE_ADDRESS": "www.edgehill.ac.uk"
    },
    {
      "UKPRN": 10007825,
      "PROVIDER_NAME": "GUILDHALL SCHOOL OF MUSIC & DRAMA",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "SILK STREET BARBICAN",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "EC2Y 8DT",
      "WEBSITE_ADDRESS": "www.gsmd.ac.uk"
    },
    {
      "UKPRN": 10007832,
      "PROVIDER_NAME": "NEWMAN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "GENNERS LANE",
      "LOCALITY": "",
      "TOWN": "BIRMINGHAM",
      "COUNTY": "",
      "POSTCODE": "B32 3NT",
      "WEBSITE_ADDRESS": "www.newman.ac.uk"
    },
    {
      "UKPRN": 10007833,
      "PROVIDER_NAME": "GLYNDWR UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "PLAS COCH",
      "STREET_NAME": "MOLD ROAD",
      "LOCALITY": "",
      "TOWN": "WREXHAM",
      "COUNTY": "CLWYD",
      "POSTCODE": "LL11 2AW",
      "WEBSITE_ADDRESS": "www.glyndwr.ac.uk"
    },
    {
      "UKPRN": 10007835,
      "PROVIDER_NAME": "ROYAL ACADEMY OF MUSIC",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "MARYLEBONE ROAD",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "NW1 5HT",
      "WEBSITE_ADDRESS": "www.ram.ac.uk"
    },
    {
      "UKPRN": 10007837,
      "PROVIDER_NAME": "ROYAL NORTHERN COLLEGE OF MUSIC",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 124,
      "STREET_NAME": "OXFORD ROAD",
      "LOCALITY": "",
      "TOWN": "MANCHESTER",
      "COUNTY": "",
      "POSTCODE": "M13 9RD",
      "WEBSITE_ADDRESS": "www.rncm.ac.uk"
    },
    {
      "UKPRN": 10007838,
      "PROVIDER_NAME": "ROYAL WELSH COLLEGE OF MUSIC AND DRAMA LIMITED",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "NORTH ROAD",
      "LOCALITY": "",
      "TOWN": "CARDIFF",
      "COUNTY": "",
      "POSTCODE": "CF10 3ER",
      "WEBSITE_ADDRESS": "www.rwcmd.ac.uk"
    },
    {
      "UKPRN": 10007842,
      "PROVIDER_NAME": "THE UNIVERSITY OF CUMBRIA",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "FUSEHILL STREET",
      "LOCALITY": "",
      "TOWN": "CARLISLE",
      "COUNTY": "",
      "POSTCODE": "CA1 2HH",
      "WEBSITE_ADDRESS": "www.cumbria.ac.uk"
    },
    {
      "UKPRN": 10007843,
      "PROVIDER_NAME": "ST MARY'S UNIVERSITY, TWICKENHAM",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "WALDEGRAVE ROAD",
      "LOCALITY": "",
      "TOWN": "TWICKENHAM",
      "COUNTY": "",
      "POSTCODE": "TW1 4SX",
      "WEBSITE_ADDRESS": "www.smuc.ac.uk"
    },
    {
      "UKPRN": 10007846,
      "PROVIDER_NAME": "SWANSEA METROPOLITAN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "MOUNT PLEASANT CAMPUS",
      "STREET_NAME": "MOUNT PLEASANT",
      "LOCALITY": "",
      "TOWN": "SWANSEA",
      "COUNTY": "WEST GLAMORGAN",
      "POSTCODE": "SA1 6ED",
      "WEBSITE_ADDRESS": "www.smu.ac.uk"
    },
    {
      "UKPRN": 10007848,
      "PROVIDER_NAME": "UNIVERSITY OF CHESTER",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "PARKGATE ROAD",
      "LOCALITY": "",
      "TOWN": "CHESTER",
      "COUNTY": "",
      "POSTCODE": "CH1 4BJ",
      "WEBSITE_ADDRESS": "www.chester.ac.uk"
    },
    {
      "UKPRN": 10007849,
      "PROVIDER_NAME": "UNIVERSITY OF ABERTAY DUNDEE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "KYDD BUILDING 40",
      "STREET_NAME": "BELL STREET",
      "LOCALITY": "",
      "TOWN": "DUNDEE",
      "COUNTY": "",
      "POSTCODE": "DD1 1HG",
      "WEBSITE_ADDRESS": "www.abertay.ac.uk"
    },
    {
      "UKPRN": 10007850,
      "PROVIDER_NAME": "UNIVERSITY OF BATH (THE)",
      "ALIAS_TEXT": "University Of Bath",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "CLAVERTON DOWN",
      "TOWN": "BATH",
      "COUNTY": "",
      "POSTCODE": "BA2 7AY",
      "WEBSITE_ADDRESS": "www.bath.ac.uk"
    },
    {
      "UKPRN": 10007851,
      "PROVIDER_NAME": "UNIVERSITY OF DERBY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "KEDLESTON ROAD",
      "LOCALITY": "",
      "TOWN": "DERBY",
      "COUNTY": "",
      "POSTCODE": "DE22 1GB",
      "WEBSITE_ADDRESS": "www.derby.ac.uk"
    },
    {
      "UKPRN": 10007852,
      "PROVIDER_NAME": "UNIVERSITY OF DUNDEE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "PERTH ROAD",
      "LOCALITY": "",
      "TOWN": "DUNDEE",
      "COUNTY": "",
      "POSTCODE": "DD1 4HN",
      "WEBSITE_ADDRESS": "www.dundee.ac.uk"
    },
    {
      "UKPRN": 10007854,
      "PROVIDER_NAME": "CARDIFF METROPOLITAN UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "PO BOX 377",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "LLANDAFF",
      "TOWN": "CARDIFF",
      "COUNTY": "",
      "POSTCODE": "CF5 2SG",
      "WEBSITE_ADDRESS": "www.cardiffmet.ac.uk"
    },
    {
      "UKPRN": 10007855,
      "PROVIDER_NAME": "SWANSEA UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "SINGLETON PARK",
      "LOCALITY": "",
      "TOWN": "SWANSEA",
      "COUNTY": "WEST GLAMORGAN",
      "POSTCODE": "SA2 8PP",
      "WEBSITE_ADDRESS": "www.swan.ac.uk"
    },
    {
      "UKPRN": 10007856,
      "PROVIDER_NAME": "PRIFYSGOL ABERYSTWYTH",
      "ALIAS_TEXT": "Aberystwyth University",
      "FLAT_NAME_NUMBER": "PO BOX 2",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "",
      "TOWN": "ABERYSTWYTH",
      "COUNTY": "DYFED",
      "POSTCODE": "SY23 2AX",
      "WEBSITE_ADDRESS": "www.aber.ac.uk"
    },
    {
      "UKPRN": 10007857,
      "PROVIDER_NAME": "BANGOR UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "COLLEGE ROAD",
      "LOCALITY": "",
      "TOWN": "BANGOR",
      "COUNTY": "GWYNEDD",
      "POSTCODE": "LL57 2DG",
      "WEBSITE_ADDRESS": "www.bangor.ac.uk"
    },
    {
      "UKPRN": 10007858,
      "PROVIDER_NAME": "UNIVERSITY OF WALES: TRINITY SAINT DAVID",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "COLLEGE ROAD",
      "LOCALITY": "",
      "TOWN": "CARMARTHEN",
      "COUNTY": "",
      "POSTCODE": "SA31 3EP",
      "WEBSITE_ADDRESS": "www.trinitysaintdavid.ac.uk"
    },
    {
      "UKPRN": 10008010,
      "PROVIDER_NAME": "STRANMILLIS UNIVERSITY COLLEGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "STRANMILLIS ROAD",
      "LOCALITY": "",
      "TOWN": "BELFAST",
      "COUNTY": "",
      "POSTCODE": "BT9 5DY",
      "WEBSITE_ADDRESS": "www.stran.ac.uk"
    },
    {
      "UKPRN": 10008017,
      "PROVIDER_NAME": "TRINITY LABAN CONSERVATOIRE OF MUSIC AND DANCE LTD",
      "ALIAS_TEXT": "Trinity Laban Conservatoire Of Music and Dance",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "KING CHARLES COURT",
      "STREET_NAME": "OLD ROYAL NAVAL COLLEGE KING WILLIAM WALK",
      "LOCALITY": "",
      "TOWN": "LONDON",
      "COUNTY": "",
      "POSTCODE": "SE10 9JF",
      "WEBSITE_ADDRESS": "www.trinitylaban.ac.uk"
    },
    {
      "UKPRN": 10008026,
      "PROVIDER_NAME": "ST MARY'S UNIVERSITY COLLEGE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 191,
      "STREET_NAME": "FALLS ROAD",
      "LOCALITY": "",
      "TOWN": "BELFAST",
      "COUNTY": "",
      "POSTCODE": "BT12 6FE",
      "WEBSITE_ADDRESS": "www.stmarys-belfast.ac.uk"
    },
    {
      "UKPRN": 10008574,
      "PROVIDER_NAME": "UNIVERSITY OF WALES PRIFYSGOL CYMRU",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "KING EDWARD VII AVENUE",
      "LOCALITY": "",
      "TOWN": "CARDIFF",
      "COUNTY": "",
      "POSTCODE": "CF10 3NS",
      "WEBSITE_ADDRESS": "www.wales.ac.uk"
    },
    {
      "UKPRN": 10008640,
      "PROVIDER_NAME": "FALMOUTH UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "Woodlane Campus",
      "STREET_NAME": "Woodlane",
      "LOCALITY": "",
      "TOWN": "Falmouth",
      "COUNTY": "Cornwall",
      "POSTCODE": "TR11 4RH",
      "WEBSITE_ADDRESS": "www.falmouth.ac.uk"
    },
    {
      "UKPRN": 10008816,
      "PROVIDER_NAME": "NORTHERN SCHOOL OF CONTEMPORARY DANCE",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 98,
      "STREET_NAME": "CHAPELTOWN ROAD",
      "LOCALITY": "",
      "TOWN": "LEEDS",
      "COUNTY": "",
      "POSTCODE": "LS7 4BH",
      "WEBSITE_ADDRESS": "www.nscd.ac.uk"
    },
    {
      "UKPRN": 10014001,
      "PROVIDER_NAME": "UNIVERSITY CAMPUS SUFFOLK LTD",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "WATERFRONT BUILDING 19-21",
      "STREET_NAME": "NEPTUNE QUAY",
      "LOCALITY": "",
      "TOWN": "IPSWICH",
      "COUNTY": "",
      "POSTCODE": "IP4 1QJ",
      "WEBSITE_ADDRESS": "www.ucs.ac.uk"
    },
    {
      "UKPRN": 10034449,
      "PROVIDER_NAME": "LEEDS COLLEGE OF MUSIC",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": 3,
      "STREET_NAME": "QUARRY HILL",
      "LOCALITY": "",
      "TOWN": "LEEDS",
      "COUNTY": "",
      "POSTCODE": "LS2 7PD",
      "WEBSITE_ADDRESS": "www.lcm.ac.uk"
    },
    {
      "UKPRN": 10037449,
      "PROVIDER_NAME": "UNIVERSITY OF ST MARK & ST JOHN",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "DERRIFORD ROAD",
      "LOCALITY": "DERRIFORD",
      "TOWN": "PLYMOUTH",
      "COUNTY": "",
      "POSTCODE": "PL6 8BH",
      "WEBSITE_ADDRESS": "marjon.ac.uk"
    },
    {
      "UKPRN": 10040812,
      "PROVIDER_NAME": "HARPER ADAMS UNIVERSITY",
      "ALIAS_TEXT": "",
      "FLAT_NAME_NUMBER": "",
      "BUILDING_NAME_NUMBER": "",
      "STREET_NAME": "",
      "LOCALITY": "Edgmond",
      "TOWN": "Newport",
      "COUNTY": "",
      "POSTCODE": "TF10 8NB",
      "WEBSITE_ADDRESS": "www.harper-adams.ac.uk"
    }
  ]